source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.8'

gem 'rails', '~> 6.1.4', '>= 6.1.4.4'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'

gem 'figaro'
gem 'rack-cors'
gem 'active_model_serializers'

gem 'devise'
gem 'devise-jwt'
gem 'omniauth-google-oauth2'
gem 'omniauth-rails_csrf_protection'

gem 'kaminari'
gem 'ransack'
gem 'dotenv-rails'

gem 'rspec-rails'

gem 'bootsnap', '>= 1.4.4', require: false


group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
